### ISSUE TITLE
No space left on device while `docker build`

### ISSUE THREAD

**Issue by wwarlock** [biemond/docker-database-puppet#3]
The command `docker build -t oracle/database12101 .` throwed error.

```
...
Step 15 : COPY linuxamd64_12c_database_1of2.zip /software/                                                           
Untar re-exec error: exit status 1: output: write /software/linuxamd64_12c_database_1of2.zip: no space left on device

```

That strange because of space is enough on my disk, so that error is in the docker image.

```
10:30:44 wwarlock@Pc-2 docker-database-puppet git:(master)$ df -h                                                    
Файловая система Размер Использовано  Дост Использовано% Cмонтировано в                                              
C:                 466G         144G  323G           31% /cygdrive/c                                                 
```

Need advice how to fix it.

**Comment by biemond** [comment]
Are you using boot2docker ? if so you need to enlarge this iso.  There are some great sites explaining this.

Else you can use this vagrant image  box-cutter/ubuntu1404-docker with vbox or vmware fusion this VM one has a big disk for docker

Thanks

**Comment by wwarlock** [comment]
Thank you very much. It was helpfull.
I think you should include this info into the readme.

**Comment by wwarlock** [comment]
Oh, you've already this has, but it located at the end.
I think you need relocate this to the start, or make link to it from start.
